bno055:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    connection_type: "uart"
    uart_port: "/dev/ttyUSB1"
    uart_baudrate: 115200
    uart_timeout: 0.1
    data_query_frequency: 60  # there are sometimes calib failures -> lowered and seems to be gone
    calib_status_frequency: 0.2 # there are sometimes calib failures -> lowered and seems to be gone
    frame_id: "imu_link"
    operation_mode: 0x08 # 08-IMU, 0C-NDOF
    placement_axis_remap: "P2"
    acc_factor: 100.0
    mag_factor: 16000000.0
    gyr_factor: 900.0
    grav_factor: 100.0
    set_offsets: true # tuned for mode:IMU, frame: P2
    offset_acc: [0xFFE0, 0x001D, 0xFFEF]
    offset_mag: [0x0001, 0x00B2, 0xFE88]
    offset_gyr: [0x0001, 0xFFFF, 0x0001]
    ## Sensor standard deviation [x,y,z]
    ## Used to calculate covariance matrices
    ## defaults are used if parameters below are not provided
    variance_acc: [0.4077, 0.3999, 0.5908] # [m/s^2]
    variance_angular_vel: [0.0114, 0.0144, 0.0429] # [rad/s]
    variance_orientation: [0.01, 0.01, 0.01] # [rad]
    # variance_mag: [0.0, 0.0, 0.0] # [Tesla]

    #default are:
    #orientation_covariance: 0.0159
    #angular_velocity_covariance: 0.04
    #linear_acceleration_covariance: 0.017
    # my calculations:
    # Imu X: 0.0108
    # Imu Y: 0.0107
    # Imu Z: 0.3039
    # Imu W: 0.7419
    # Imu OMx: 0.0114
    # Imu OMy: 0.0144
    # Imu OMz: 0.0429
    # Imu Ax: 0.4077
    # Imu Ay: 0.3999
    # Imu Az: 0.5908
