rf2o_laser_odometry:
  ros__parameters:
    laser_scan_topic: "/lidar_horizontal/scan"
    odom_topic: "/odom_lidar_rf2o"
    publish_tf: False
    base_frame_id: "lidar_horizontal_link"
    odom_frame_id: "odom"
    init_pose_from_topic: ""
    freq: 5.0 # lidar is 6

rf2o_laser_odometry_fixer:
  ros__parameters:
    odom_topic: "/odom_lidar_rf2o"
    odom_topic_fixed: "/odom_lidar_rf2o_fixed"
    x_dot_coeff: -1.0
    yaw_dot_coeff: 1.0
    covariance: [
        0.1182, #  0.1182
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.001, # 0.0 -> giving 0.001 so ekf doesn't scream
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0408, # 0.0408
      ]
#  my calculations from test:
# Lidar Vx: 0.1182
# Lidar Vy: 0.0
# Lidar OMz: 0.0408